name: builder

on: [push, workflow_dispatch]

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build package (via docker buildx)
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=false" \
            -t opentegra:builder .
      -
        name: Get output deb
        run: mkdir output && docker run --rm -v ${GITHUB_WORKSPACE}/output:/output opentegra:builder && ls output
      -
        name: Upload .deb packages
        uses: actions/upload-artifact@v3
        with:
          path: output/*.deb 
